// SPDX-License-Identifier: AGPL-3.0-or-later
/**
 * Built-in Export Templates
 *
 * Pre-defined export templates for common game engine and data formats.
 * Users can use these as-is or as starting points for custom templates.
 */

import type { ExportTemplate } from "@/types/exportTemplate";

/** Generic JSON array export */
const JSON_ARRAY: ExportTemplate = {
    id: "json-array",
    name: "JSON Array",
    description: "Export data as a JSON array of objects. Each row becomes an object with column headers as keys.",
    outputFormat: "json",
    fieldMappings: [],
    headerTemplate: "[\n",
    rowTemplate: "  {row_json}",
    footerTemplate: "\n]",
    rowSeparator: ",\n",
    options: {
        prettyPrint: true,
        indentation: 2,
        encoding: "utf-8",
        fileExtension: "json",
        includeEmpty: false,
    },
    isBuiltIn: true,
    category: "General",
};

/** Unity ScriptableObject JSON format */
const UNITY_JSON: ExportTemplate = {
    id: "unity-scriptable-object",
    name: "Unity ScriptableObject JSON",
    description: "Export for Unity Engine ScriptableObject data tables. Compatible with Unity's JsonUtility.",
    outputFormat: "json",
    fieldMappings: [],
    headerTemplate: '{\n  "items": [\n',
    rowTemplate: "    {row_json}",
    footerTemplate: '\n  ]\n}',
    rowSeparator: ",\n",
    options: {
        prettyPrint: true,
        indentation: 4,
        encoding: "utf-8",
        fileExtension: "json",
        includeEmpty: true,
    },
    isBuiltIn: true,
    category: "Game Engines",
};

/** Unreal Engine DataTable JSON */
const UNREAL_JSON: ExportTemplate = {
    id: "unreal-datatable",
    name: "Unreal DataTable JSON",
    description: "Export for Unreal Engine DataTable format. Each row is keyed by its first column value.",
    outputFormat: "json",
    fieldMappings: [],
    headerTemplate: "[\n",
    rowTemplate: "  {\n    \"Name\": \"{0}\",\n    {row_fields}\n  }",
    footerTemplate: "\n]",
    rowSeparator: ",\n",
    options: {
        prettyPrint: true,
        indentation: 2,
        encoding: "utf-8",
        fileExtension: "json",
        includeEmpty: true,
    },
    isBuiltIn: true,
    category: "Game Engines",
};

/** Godot Resource format */
const GODOT_RESOURCE: ExportTemplate = {
    id: "godot-resource",
    name: "Godot Resource (.tres)",
    description: "Export as a Godot Engine resource file. Suitable for dialogue or data resources.",
    outputFormat: "custom",
    fieldMappings: [],
    headerTemplate: '[gd_resource type="Resource" format=3]\n\n[resource]\n',
    rowTemplate: "[sub_resource type=\"Resource\" id=\"{0}\"]\n{row_fields_godot}",
    footerTemplate: "",
    rowSeparator: "\n\n",
    options: {
        prettyPrint: true,
        indentation: 0,
        encoding: "utf-8",
        fileExtension: "tres",
        includeEmpty: false,
    },
    isBuiltIn: true,
    category: "Game Engines",
};

/** Ink dialogue format */
const INK_DIALOGUE: ExportTemplate = {
    id: "ink-dialogue",
    name: "Ink Dialogue",
    description: "Export dialogue data in Inkle's Ink scripting format. Maps character and dialogue columns.",
    outputFormat: "custom",
    fieldMappings: [],
    headerTemplate: "// Generated by Seria\n// Ink dialogue export\n\n",
    rowTemplate: "{character}: {dialogue}",
    footerTemplate: "\n\n-> END\n",
    rowSeparator: "\n",
    options: {
        prettyPrint: true,
        indentation: 0,
        encoding: "utf-8",
        fileExtension: "ink",
        includeEmpty: false,
    },
    isBuiltIn: true,
    category: "Dialogue",
};

/** Yarn Spinner dialogue format */
const YARN_DIALOGUE: ExportTemplate = {
    id: "yarn-dialogue",
    name: "Yarn Spinner",
    description: "Export dialogue data in Yarn Spinner format for Unity and other engines.",
    outputFormat: "custom",
    fieldMappings: [],
    headerTemplate: "title: ExportedDialogue\n---\n",
    rowTemplate: "{character}: {dialogue}",
    footerTemplate: "\n===\n",
    rowSeparator: "\n",
    options: {
        prettyPrint: true,
        indentation: 0,
        encoding: "utf-8",
        fileExtension: "yarn",
        includeEmpty: false,
    },
    isBuiltIn: true,
    category: "Dialogue",
};

/** XML export */
const XML_EXPORT: ExportTemplate = {
    id: "xml-generic",
    name: "XML",
    description: "Export data as XML with each row as an element. Column headers become child elements.",
    outputFormat: "xml",
    fieldMappings: [],
    headerTemplate: '<?xml version="1.0" encoding="UTF-8"?>\n<data>\n',
    rowTemplate: "  <row>\n{row_fields_xml}\n  </row>",
    footerTemplate: "\n</data>\n",
    rowSeparator: "\n",
    options: {
        prettyPrint: true,
        indentation: 2,
        encoding: "utf-8",
        fileExtension: "xml",
        includeEmpty: true,
    },
    isBuiltIn: true,
    category: "General",
};

/** YAML export */
const YAML_EXPORT: ExportTemplate = {
    id: "yaml-generic",
    name: "YAML",
    description: "Export data as a YAML list of objects. Clean, readable format for configuration files.",
    outputFormat: "yaml",
    fieldMappings: [],
    headerTemplate: "# Generated by Seria\n---\n",
    rowTemplate: "- {row_fields_yaml}",
    footerTemplate: "",
    rowSeparator: "\n",
    options: {
        prettyPrint: true,
        indentation: 2,
        encoding: "utf-8",
        fileExtension: "yaml",
        includeEmpty: false,
    },
    isBuiltIn: true,
    category: "General",
};

/** All built-in export templates */
export const BUILT_IN_TEMPLATES: ExportTemplate[] = [
    JSON_ARRAY,
    UNITY_JSON,
    UNREAL_JSON,
    GODOT_RESOURCE,
    INK_DIALOGUE,
    YARN_DIALOGUE,
    XML_EXPORT,
    YAML_EXPORT,
];

/** Template categories for grouping */
export const TEMPLATE_CATEGORIES = ["General", "Game Engines", "Dialogue"];
